[build]
  command = "dotnet publish -c Release -o build"
  publish = "build/wwwroot"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

  [[plugins]]
  package = "netlify-plugin-dotnet"

  [plugins.inputs]
    version = "9.0.304"

