[build]
  base = "PortfolioBlazorVersion"
  command = "dotnet publish PortfolioBlazorVersion.csproj -c Release -o ../build"
  publish = "../build/wwwroot"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
